import {
  extractReasoningMiddleware,
  generateText,
  stepCountIs,
  wrapLanguageModel,
  type UIMessage,
} from "ai";
import { chatModelFromSettings } from "../global/ai";
import { resolveDefaultChatModel } from "./default-model";
import { getProviderSetting } from "../db/provider-settings";
import { buildConnectorTools } from "./connectors";
import {
  claimCronJob,
  createCronJobRun,
  deleteCronJob,
  findDueCronJobs,
  updateCronJob,
  type CronJob,
} from "../db/cron";
import { createMessage, updateMessage } from "../db/conversations";
import { getAgent, listAgentMembers } from "../db/agents";
import { getUser } from "../db/users";
import {
  buildMemorySystemPrompt,
  buildMemoryTools,
  buildRelevantMemoriesBlock,
  type MemoryScope,
} from "./memory";
import { searchTools, webSearchPrompt } from "./search";
import { buildDateTools, dateToolPrompt } from "./date-tool";
import { buildFileTools, filesPrompt } from "./files";
import { buildNoteTools, notesPrompt } from "./notes";
import { buildConversationSearchTools, conversationSearchPrompt } from "./conversation-search";
import { loadSystemPrompt } from "./system-prompt";
import { nextRunAfter } from "./cron-schedule";

// The job's stored provider/model resolved against the creator's current
// provider settings, exactly like a chat request. Falls back to the creator's
// default model when unset — or when the provider has been deconfigured since
// the job was created, so old jobs keep running. null when the creator has no
// default model either (the run records an error).
async function resolveJobModel(job: CronJob) {
  if (!job.provider) return resolveDefaultChatModel(job.userId);
  const setting = await getProviderSetting(job.userId, job.provider);
  const modelId = job.model ?? setting?.settings.model;
  if (!setting || !modelId) return resolveDefaultChatModel(job.userId);
  return chatModelFromSettings(job.provider, setting.settings, modelId);
}

// Best-effort short display name for an untitled job, generated by the job's
// own model (no tools). A failure here must never fail the run.
async function generateJobTitle(
  model: Parameters<typeof generateText>[0]["model"],
  prompt: string
): Promise<string | null> {
  try {
    const result = await generateText({
      model,
      system:
        "You name scheduled tasks. Reply with a short title (3-6 words) for the given task prompt — title case, no quotes, no trailing punctuation, nothing else.",
      prompt,
    });
    const title = result.text.trim().replace(/^["']+|["'.]+$/g, "").slice(0, 80);
    return title || null;
  } catch {
    return null;
  }
}

// Mirrors the conversation route's prompt assembly (api/agent/conversation.ts),
// but non-streaming. The result lands as a new private conversation owned by
// the job's creator, so it shows up in their sidebar like any chat. Untitled
// jobs get a title generated here and saved on the job.
async function executeCronJob(
  job: CronJob
): Promise<{ conversationId: string; title: string | null }> {
  const [agent, members, user] = await Promise.all([
    getAgent(job.agentId),
    listAgentMembers(job.agentId),
    getUser(job.userId),
  ]);
  if (!agent) throw new Error("Agent no longer exists");
  if (!user) throw new Error("User no longer exists");
  if (!members.some((m) => m.userId === user.id)) {
    throw new Error("Job creator is no longer a member of the agent");
  }

  const scope: MemoryScope = {
    agentId: agent.id,
    speaker: { id: user.id, name: user.name },
    members,
  };

  // Job runs respect the agent's chat-memory setting like a normal turn: when
  // it is off they get no memory prompt, recalled memories, or memory tools.
  const [basePrompt, memoriesBlock, memorySystemPrompt] = await Promise.all([
    loadSystemPrompt(),
    agent.chatMemoryEnabled ? buildRelevantMemoriesBlock(scope, job.prompt) : null,
    agent.chatMemoryEnabled
      ? buildMemorySystemPrompt(scope, {
          sharedConversation: false,
          customPrompt: agent.chatMemoryPrompt,
        })
      : "",
  ]);

  const userMessage: UIMessage = {
    id: crypto.randomUUID(),
    role: "user",
    metadata: { userId: user.id, userName: user.name },
    parts: [
      ...(memoriesBlock ? [{ type: "text" as const, text: memoriesBlock }] : []),
      { type: "text", text: job.prompt },
    ],
  };

  // Persist before generating (parity with the chat route): the conversation —
  // and the file-tool folder keyed by its id — exists even if the model call fails.
  const conversation = await createMessage({
    agentId: agent.id,
    userId: user.id,
    shared: false,
    messages: [userMessage],
  });

  const agentPrompt = agent.systemPrompt?.trim()
    ? `Instructions from this agent's owner:\n${agent.systemPrompt.trim()}`
    : "";
  const resolvedModel = await resolveJobModel(job);
  if (!resolvedModel) {
    throw new Error(
      "No model configured. Pick a model for this job, or set a default model in Settings → Models."
    );
  }
  const model = wrapLanguageModel({
    model: resolvedModel,
    middleware: extractReasoningMiddleware({ tagName: "think" }),
  });

  // Connector tools (e.g. Gmail) follow the creator like a normal chat turn:
  // connected connectors only, filtered by their per-agent permission levels.
  const connectorToolset = await buildConnectorTools({
    userId: user.id,
    agentId: agent.id,
  });

  const system = [
    basePrompt,
    agentPrompt,
    memorySystemPrompt,
    webSearchPrompt,
    dateToolPrompt,
    filesPrompt,
    notesPrompt,
    conversationSearchPrompt,
    connectorToolset.prompt,
    "This is a scheduled recurring task running unattended: the user is not present to answer questions, so complete the task with the information available and present the result directly.",
  ]
    .filter(Boolean)
    .join("\n\n");

  const result = await generateText({
    model,
    system,
    prompt: memoriesBlock ? `${memoriesBlock}\n\n${job.prompt}` : job.prompt,
    tools: {
      ...(agent.chatMemoryEnabled ? buildMemoryTools(scope) : {}),
      ...searchTools,
      ...buildDateTools(job.timezone),
      ...buildFileTools(conversation.id),
      ...buildNoteTools(agent.id, user.id),
      ...buildConversationSearchTools({
        agentId: agent.id,
        viewerId: user.id,
        currentConversationId: conversation.id,
      }),
      ...connectorToolset.tools,
    },
    stopWhen: stepCountIs(8),
  });

  await updateMessage(conversation.id, {
    messages: [
      userMessage,
      {
        id: crypto.randomUUID(),
        role: "assistant",
        parts: [{ type: "text", text: result.text }],
      } satisfies UIMessage,
    ],
  });

  let title = job.title;
  if (!title) {
    title = await generateJobTitle(model, job.prompt);
    if (title) await updateCronJob(job.id, { title });
  }
  return { conversationId: conversation.id, title };
}

export async function runCronJob(job: CronJob): Promise<void> {
  const startedAt = new Date();
  // Run rows copy the job's user/agent/title/prompt so the history survives the job.
  const base = {
    jobId: job.id,
    userId: job.userId,
    agentId: job.agentId,
    title: job.title,
    prompt: job.prompt,
  };
  try {
    const { conversationId, title } = await executeCronJob(job);
    await createCronJobRun({
      ...base,
      title,
      conversationId,
      status: "success",
      startedAt,
      finishedAt: new Date(),
    });
    // One-time jobs (reminders) are done after their first successful run; a
    // failed run keeps the job so it retries on its fallback schedule.
    if (job.recurrence === "once") await deleteCronJob(job.id);
  } catch (error) {
    await createCronJobRun({
      ...base,
      status: "error",
      error: error instanceof Error ? error.message : String(error),
      startedAt,
      finishedAt: new Date(),
    });
  }
}

/**
 * One scheduler pass: claim and run every due job. A job missed while the
 * server was down runs once and then skips ahead to its next future slot
 * (no catch-up backlog). The claim is a compare-and-swap on nextRunAt, so
 * overlapping ticks (or a second server) never double-run a job.
 */
export async function cronTick(now = new Date()): Promise<void> {
  const due = await findDueCronJobs(now);
  for (const job of due) {
    let next = nextRunAfter(job, job.nextRunAt);
    while (next.getTime() <= now.getTime()) next = nextRunAfter(job, next);
    if (!(await claimCronJob(job.id, job.nextRunAt, next))) continue;
    await runCronJob(job);
  }
}

const TICK_MS = 60_000;

export function startCronScheduler(): NodeJS.Timeout {
  return setInterval(() => {
    cronTick().catch((error) => console.error("Cron scheduler tick failed:", error));
  }, TICK_MS);
}
